### ISSUE TITLE
DateCreated, DateModified

### ISSUE THREAD

**Issue by tim-deighton** [kendraio/kendraio-app#89] opened 2019-11-06 11:08 UTC
we need these dates by default on each record. will be useful when synchronizing

**Comment by tim-deighton** [comment] 2019-11-06 11:44
this should be 'service' side not in the workflow. ???

**Comment by dahacouk** [comment] 2019-12-02 11:49
Merge with #91

**Comment by dahacouk** [comment] 2019-12-02 12:45
Duplicate of #91

**Comment by dahacouk** [comment] 2019-12-02 12:45
Duplicate of #91

**Closed by dahacouk** 2019-12-02 12:46 UTC
