### ISSUE TITLE
Multiple identities per provider

### ISSUE THREAD

**Issue by darrenmothersele** [kendraio/kendraio-app#41] opened 2019-09-25 08:23 UTC
Ability to add multiple identities per provider.

For this we need to design some mechanism for declaring separate "spaces" where operations know which identity to use from the context. Probably needs some mechanism for selecting which identity is to be used (per workflow) if multiple exist.

**Comment by darrenmothersele** [comment] 2019-09-25 08:26
Combine this with more generic handling of profile data from all adapters. Refactor identities page to separate profile data, identities, and authentication tokens.

**Comment by dahacouk** [comment] 2019-12-02 12:10
Merge with #98

**Comment by dahacouk** [comment] 2019-12-02 12:48
Duplicate of #98

**Closed by dahacouk** 2019-12-02 12:48 UTC
Labels: enhancement
