### ISSUE TITLE
Bubble-up the WorkFlow

### ISSUE THREAD

**Issue by tim-deighton** [kendraio/kendraio-app#112] opened 2019-12-23 15:10 UTC
As a User I would like to refresh a value at the top of a WorkFlow (maybe in a grid) when I change a value at the bottom of the WorkFlow, without refreshing the page.

**Comment by tim-deighton** [comment] 2019-12-23 15:11
Maybe a good candidate for NGRX??!!

**Comment by darrenmothersele** [comment] 2020-04-17 12:35
duplicate of #42

**Closed by darrenmothersele** 2020-04-17 12:35 UTC
Labels: enhancement, improvement
